### ISSUE TITLE
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:

### ISSUE THREAD

**Issue by AbhiAndroidManiac** [android/plaid#818]
Building the project in Android studio 3.6 rc version giving above error. And the project doesnt build.

**Comment by Android1968** [comment]
Same error here,trying to import a project.

**Comment by Aiuspaktyn** [comment]
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:

Same problem on Windows, on Mac it's working fine

**Comment by AbhiAndroidManiac** [comment]
> 
> 
> Building the project in Android studio 3.6 rc version giving above error. And the project doesnt build.

I resolved it by changing the build gradle to existing android studio version.

**Comment by carloskinn** [comment]
> > Building the project in Android studio 3.6 rc version giving above error. And the project doesnt build.
> 
> I resolved it by changing the build gradle to existing android studio version.

Could you explain the process?

**Comment by Nmanou** [comment]
i have same issue after updating to 3.6.1. if anyone have a solution please tell me. it gives me
 headache.

**Comment by carloskinn** [comment]
I solved it set the gradle version of the project to the newest version 6.2.1 on the project structure options.

![image](https://user-images.githubusercontent.com/3351420/75755922-86821080-5d27-11ea-82a3-3cc2bc286f05.png)


> i have same issue after updating to 3.6.1. if anyone have a solution please tell me. it gives me
> headache.

**Comment by Nmanou** [comment]
> I solved it changing the gradle version of the project to the newest version 6.2.1 on the project structure options.
> 
> ![image](https://user-images.githubusercontent.com/3351420/75755922-86821080-5d27-11ea-82a3-3cc2bc286f05.png)
> 
> > i have same issue after updating to 3.6.1. if anyone have a solution please tell me. it gives me
> > headache.

it resolve my issue. thanku so much for your time................

**Comment by YOON677** [comment]
Why the above solution requires you to reconfigure gradle after every project creation.

**Comment by daniel3133** [comment]
> لقد قمت بحلها بتغيير الإصدار التدريجي للمشروع إلى الإصدار الأحدث 6.2.1 على خيارات هيكل المشروع.
> 
> ![صورة](https://user-images.githubusercontent.com/3351420/75755922-86821080-5d27-11ea-82a3-3cc2bc286f05.png)
> 
> > لدي نفس المشكلة بعد التحديث إلى 3.6.1. إذا كان أي شخص لديه حل من فضلك قل لي. يسبب لي 
> > الصداع.

I need help please

**Comment by Innocent97** [comment]
I currently have the same issue and I have tried the suggested solutions. Unfortunately, none of them worked. Anyone who can help?

**Comment by markosekula** [comment]
I also have the same problem, installed Android Studio v3.6.2, 3 days ago. Does someone have a proposal about what I can do?

**Comment by markosekula** [comment]
> I currently have the same issue and I have tried the suggested solutions. Unfortunately, none of them worked. Anyone who can help?

Did you find some solution in meanwhile?

**Comment by Anaeligbo-Joseph** [comment]
Checked my **build.gradle (project)** file for error fixed the problem. It was badly reconstructed at run-time.

**Comment by reimondpc** [comment]
build.gradle

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }
it's working fine

**Comment by arpit999** [comment]
> I solved it changing the gradle version of the project to the newest version 6.2.1 on the project structure options.
> 
> ![image](https://user-images.githubusercontent.com/3351420/75755922-86821080-5d27-11ea-82a3-3cc2bc286f05.png)
> 
> > i have same issue after updating to 3.6.1. if anyone have a solution please tell me. it gives me
> > headache.

You are a life saver

**Comment by sary-huang** [comment]
> I solved it changing the gradle version of the project to the newest version 6.2.1 on the project structure options.
> 
> ![image](https://user-images.githubusercontent.com/3351420/75755922-86821080-5d27-11ea-82a3-3cc2bc286f05.png)
> 
> > i have same issue after updating to 3.6.1. if anyone have a solution please tell me. it gives me
> > headache.

tks,the problem have been resolved by update gradle version to 6.2.1

**Comment by Parvane1989** [comment]
I have same issue after updating to 3.6.3. I solved it by changing the API level and Android version in the start of creating new project.
![Inkederrore_LI](https://user-images.githubusercontent.com/65833757/82742058-fe9c1900-9d0d-11ea-9681-31451072658f.jpg)

**Comment by Adorna-R** [comment]
In my case, the name had an apostrophe, so I had to put a "\" before it in the settings.gradle.
For example, 'D'Antojo' → 'D\'Antojo'

**Comment by abrahimzaman** [comment]
I have the same problem. will someone fix this error.

**Comment by afzarahnaushad** [comment]
After changing at program structure to 6.2.1 it still have the same error. anyone know how to solve it?

**Comment by abrahimzaman** [comment]
Please Change Your Gradle Build tools to Latest Version. It will be fixed
there only.


Abrahim Zaman A,
Programmer & Developer,
at ABRA Software Foundation,

47 Way Near Grand Mosque,
Hassa Balakot, Mansehra,
KPK, Pakistan, Asia

**Comment by Rohitohlyan66** [comment]
> In my case, the name had an apostrophe, so I had to put a "" before it in the settings.gradle.
> For example, 'D'Antojo' → 'D\'Antojo'

Thanks Dude ,it worked for me

**Comment by ZionCloud** [comment]
I also have the same problem, installed Android Studio v3.6.4, 3 days ago. Does someone have a proposal about what I can do?

**Comment by Mensh123** [comment]
I have Android Studio version 4.1...
I tryed changing to grandle version 6.2.1 but I got an error this would be too old... :-(

**Comment by tpjwm** [comment]
I had this issue, and nothing would work, until I reinstalled everything into the same drive. Originally had Android Studio on a portable drive but apparently that was causing issues. So I just put reinstalled it on the drive with my windows installation.

**Comment by ayeshajagirdar** [comment]
> i have same issue after updating to 3.6.1. if anyone have a solution please tell me. it gives me
> headache.

just restore the android  studio to default settings.
close your current project and then goto to configure in bottom and you have option "Restore Default Settings" Then click okay for everything it will be working fine

**Comment by ayeshajagirdar** [comment]
> i have same issue after updating to 3.6.1. if anyone have a solution please tell me. it gives me
> headache.

just restore the android studio to default settings.
close your current project and then goto to configure in bottom and you have option "Restore Default Settings" Then click okay for everything it will be working fine

**Comment by saumilvaghelaGS** [comment]
You have to check the error logs properly, My Issue was I have changed the JDK version and it's conflicting the problem to generate build and compile the project.

**Comment by mohan1361** [comment]
![Screenshot 2022-01-06 23 38 31](https://user-images.githubusercontent.com/68941763/148430149-b6446af6-3665-43b3-8a1d-4565f932ed96.png)
You go to the project structure and go to the dependency section, download updates will be coming, after updating the build will be successful.
 'androidx.annotation:annotation:1.3.0' and update  gradel JDK Embedded JDK Version  in gradel settings.

**Comment by Husnainfarooq** [comment]
> Building the project in Android studio 3.6 rc version giving above error. And the project doesnt build.

i resolved it with re-import the project android studio suggestion

**Comment by Cyclotron17** [comment]
How to resolve this issue in the latest android studio versions?
